String.toLocaleString({

	"it": {
    "%game-intro"           : "Join the <strong>HUSKYGAME!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "",
    "%credits"              : "",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-HUSKYGAME #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Beautiful Husky',
    '%4'                    : 'Funny Husky',
    '%8'                    : 'Cute Husky',
    '%16'                   : 'Loyal Husky',
    '%32'                   : 'Huskygraphy',
    '%64'                   : 'Royal Husky',
    '%128'                  : 'Neon Husky',
    '%256'                  : 'Husky Puppy',
    '%512'                  : 'Husky Pack',
    '%1024'                 : 'Bold Husky',
    '%2048'                 : 'Calm Husky',
    '%4096'                 : 'Cue Husky Puppy',
    '%8192'                 : 'King Husky',
    '%p0'                   : 'Beautiful Husky',
    '%p4'                   : 'Funny Husky',
    '%p8'                   : 'Cute Husky',
    '%p16'                  : 'Loyal Husky',
    '%p32'                  : 'Huskygraphy',
    '%p64'                  : 'Royal Husky',
    '%p128'                 : 'Neon Husky',
    '%p256'                 : 'Husky Puppy',
    '%p512'                 : 'Husky Pack',
    '%p1024'                : 'Bold Husky',
    '%p2048'                : 'Calm Husky',
    '%p4096'                : 'Cue Husky Puppy',
    '%p8192'                : 'King Husky'

	},

  "en": {
    "%game-intro"           : "Join the <strong>HUSKYGAME!</strong>",
    "%restart-button"       : "Play Again",
    "%keep-playing-button"  : "Keep going",
    "%retry-button"         : "Retry",
    "%game-won"             : "You win!",
    "%game-over"            : "Game over!",
    "%game-explanation"     : "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer"           : "",
    "%credits"              : "",
    "%tweet1"               : "I scored \"",
    "%tweet2"               : " at 2048-HUSKYGAME #2048game",
    "%tile-legend"          : "<strong class=\"important\">Tile Legend:</strong>",
    '%2'                    : 'Beautiful Husky',
    '%4'                    : 'Funny Husky',
    '%8'                    : 'Cute Husky',
    '%16'                   : 'Loyal Husky',
    '%32'                   : 'Huskygraphy',
    '%64'                   : 'Royal Husky',
    '%128'                  : 'Neon Husky',
    '%256'                  : 'Husky Puppy',
    '%512'                  : 'Husky Pack',
    '%1024'                 : 'Bold Husky',
    '%2048'                 : 'Calm Husky',
    '%4096'                 : 'Cue Husky Puppy',
    '%8192'                 : 'King Husky',
    '%p0'                   : 'Beautiful Husky',
    '%p4'                   : 'Funny Husky',
    '%p8'                   : 'Cute Husky',
    '%p16'                  : 'Loyal Husky',
    '%p32'                  : 'Huskygraphy',
    '%p64'                  : 'Royal Husky',
    '%p128'                 : 'Neon Husky',
    '%p256'                 : 'Husky Puppy',
    '%p512'                 : 'Husky Pack',
    '%p1024'                : 'Bold Husky',
    '%p2048'                : 'Calm Husky',
    '%p4096'                : 'Cue Husky Puppy',
    '%p8192'                : 'King Husky'
  }
});
